### PR TITLE
Use JavaScriptNext as the base for JSX syntax highlighting

### PR DESCRIPTION
**Pull request by zertosh**
Not sure if this is a _good idea_, but it's worth considering:

I've combined [Benvie/JavaScriptNext](https://github.com/Benvie/JavaScriptNext.tmLanguage) (which has really good ES6 support) with [yungsters/sublime](https://github.com/yungsters/sublime)'s for JSX support. Since the React community tends to write ES6 flavored JSX, it makes sense to have good ES6 support.

I took [these lines](https://github.com/yungsters/sublime/blob/10980f0/tmLanguage/JavaScript%20%28JSX%29.JSON-tmLanguage#L450-L558) from @yungsters version. Only changing the `jsx-evaluated-code` section so it included `#core` instead of `#expression`. And added them to @benvie's [Benvie/JavaScriptNext.tmLanguage](https://github.com/Benvie/JavaScriptNext.tmLanguage/blob/41c1b8b/JavaScriptNext.YAML-tmLanguage), as the diff in the comment shows.

I'm not sure if @benvie would even be ok with this (there is no license info). I'm not sure if this is 100% correct, but from cursory use, it seems to work just fine. Maybe someone with more tmLanguage experience can vet this?

### CODE REVIEW

**Comment by zertosh** [comment]
Closing in favor of https://github.com/6to5/6to5-sublime

**Comment by jgebhardt** [comment]
@zertosh Big apologies, as I haven't been very active on this project in a while! 6to5-sublime is great. Are you (still) interested in merging the two packages? Consumers would be oh so happy :)

**Comment by zertosh** [comment]
hey @jgebhardt np. what exactly do you mean by "merging the two projects"?

**Comment by jgebhardt** [comment]
Well, it seems that with the creation of 6to5-sublime, there now exist 2 packages in package control that do the exact same thing, yet need to be maintained simultaneously. I would prefer deprecating one of the two.

**Comment by zertosh** [comment]
@jgebhardt I get that, it makes sense. Would you be open to endorsing 6to5-sublime as the suggested syntax definition?

**Comment by jgebhardt** [comment]
Totally! You mean as in rebase sublime-react on top of the 6to5-sublime syntax definitions?

**Comment by zertosh** [comment]
@jgebhardt No, 6to5-sublime is pretty complete already, I meant like sublime-react closes up and sends everyone to 6to5-sublime

**Comment by mathieumg** [comment]
Or babel-sublime? Haha.

**Comment by zertosh** [comment]
lol yup, new name :smile: https://github.com/babel/babel-sublime

**Comment by zertosh** [comment]
@jgebhardt Have you given it any thought? Do you have another suggestion?

I just added a few screenshots highlighting some of the improvements I've made to the JSX matching https://github.com/babel/babel-sublime#screenshots

**Pull request closed without merging**
