### PR TITLE
'this.refs' snippet

### PR DESCRIPTION
**Pull request by jackunion**

### CODE REVIEW

**Comment by jgebhardt** [comment]
Thank you. Sorry for the huge delay!

**Comment by jackunion** [comment]
It's alright : ]
Actually, you couldn't have chosen a better time to merge this.
I'd like to ask you for a favor - I'm working on React project right now and I need a fresh look and possibly an advice and code review. Do you by any chance have spare time or know someone who can help? I'd really appreciate that!

**Comment by jgebhardt** [comment]
Sure thing, feel free to shoot me an email!

**Comment by jackunion** [comment]
@jgebhardt thank you!

I didn't find any address, so I just used the one on your website. Hope it's okay.

**Comment by jgebhardt** [comment]
@jackunion git makes it easy to stalk people ;)
`git show -s --format="%ae"`

**Pull request merged**
